source/ssn_binh_uat/protected/modules/admin/controllers/CompanyController.php
<?php

class CompanyController extends AdminController {

	public $pluralTitle = 'Company Profile';
	public $singleTitle = 'Company';
	public $cannotDelete = array();

	public function actionSetDefaultLogo($id) {
		$model = $this->loadModel($id);
		$model->image = '';
		$model->update('image');
		$this->redirect(array('view', 'id'=>$id));
	}
	
	public function actionIndex() {

		$model = new SsnCompany('search');
		$model->unsetAttributes();  // clear any default values
		if (isset($_GET['SsnCompany']))
			$model->attributes = $_GET['SsnCompany'];

		$this->pageTitle = 'Company';
		$this->render('index', array(
			'model' => $model, 'actions' => $this->listActionsCanAccess,
		));
	}
	
	public function actionView($id) {
		$model = $this->loadModel($id);
        if (isset($_POST['SsnCompany'])) {
            $model->attributes = $_POST['SsnCompany'];
            if ($model->save()) {
                $model->saveImage('image');
                Yii::app()->user->setFlash('success', "Your profile has been successfully changed.");
				$this->redirect(array('view', 'id'=>$id));
            }
        }
		$this->pageTitle = "Company '{$model->name}'";
		$this->render('view', array('model'=>$model));
	}

	public function actionPartner($id) {
		$model = $this->loadModel($id);
		$search = new SsnPartner('search');
		$search->from_user_id = $search->to_user_id = $model->user_id;
		$model->searchModel = $search;
		$this->pageTitle = "Company '{$model->name}'";
		$this->render('partner', array('model'=>$model));
	}

	public function actionSample($id) {

        print_r($_GET['SsnSampleSearch_sort']);
        //exit;

		$model = $this->loadModel($id);
		$search = new SsnSampleSearch();
		$search->user_id = $model->user_id;
		$model->searchModel = $search;
		$this->pageTitle = "Company '{$model->name}'";
		$this->render('sample', array('model'=>$model));
	}

	public function actionDeleteSample($id) {
		if (Yii::app()->request->isPostRequest) {
			// we only allow deletion via POST request
			if (!in_array($id, $this->cannotDelete)) {
				if ($model = SsnSample::model()->findByPk($id)) {
					$model->delete();
				}

				// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
				if (!isset($_GET['ajax']))
					$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
			}
		}
	}
	
	public function actionDelete($id) {
		if (Yii::app()->request->isPostRequest) {
			// we only allow deletion via POST request
			if (!in_array($id, $this->cannotDelete)) {
				if ($model = SsnPartner::model()->findByPk($id)) {
					$model->delete();
				}

				// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
				if (!isset($_GET['ajax']))
					$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
			}
		} else {
			throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
		}
	}

    /*
     * Bulk delete
     * If you don't want to delete some specified record please configure it in global $cannotDetele variable
     */

    public function actionDeleteAll() {
        $shouldDelete = $_POST['ssn-company-grid_c0'];

        if (!empty($shouldDelete)) {
            SsnCompany::model()->deleteAll('id in (' . implode(',', $shouldDelete) . ')');
            Yii::app()->user->setFlash('success', 'Your selected records have been deleted.');
        }
        else
            Yii::app()->user->setFlash('error', 'No records deleted.');

        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
    }
	
	public function actionApprove($id) {
		$partner = SsnPartner::model()->findByPk($id);
		if ($partner) {
			$partner->status = SsnPartner::STATUS_APPROVE;
			$partner->approve_by = Yii::app()->user->id;
			if ($partner->update(array('status'))) {
				SendEmail::partnerApproveRequest($partner);
			}
		}
		echo '1';
	}
	
	public function loadModel($id) {
		//need this define for inherit model case. Form will render parent model name in control if we don't have this line
		$model = SsnCompany::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $model;
	}

}

source/ssn_binh_uat/protected/modules/admin/controllers/SampleController.php
<?php

class SampleController extends AdminController {

	public $pluralTitle = 'Samples';
	public $singleTitle = 'Sample';
	public $cannotDelete = array();

	public function actionView($id) {
		$model = SsnSample::model()->findByPk($id);
		$model->scenario = 'view';
		$this->pageTitle = "Sample Detail";
		$this->render('view', array(
			'model' => $model,
		));
	}
	
	public function actionDelete($id) {
		try {
			if (Yii::app()->request->isPostRequest) {
				// we only allow deletion via POST request
				if (!in_array($id, $this->cannotDelete)) {
					if ($model = $this->loadModel($id)) {
						if ($model->delete())
							Yii::log("Delete record " . print_r($model->attributes, true), 'info');
					}

					// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
					if (!isset($_GET['ajax']))
						$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
				}
			} else {
				Yii::log("Invalid request. Please do not repeat this request again.");
				throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
			}
		} catch (Exception $e) {
			Yii::log("Exception " . print_r($e, true), 'error');
			throw new CHttpException($e);
		}
	}

	public function actionIndex() {


		$model = new SsnSampleSearch('searchAdmin');
		$model->unsetAttributes();  // clear any default values
		if (isset($_GET['SsnSampleSearch']))
			$model->attributes = $_GET['SsnSampleSearch'];

		$this->pageTitle = 'Samples';
		$this->render('index', array(
			'model' => $model, 'actions' => $this->listActionsCanAccess,
		));
	}

	/*
	 * Bulk delete
	 * If you don't want to delete some specified record please configure it in global $cannotDelete variable
	 */

	public function actionDeleteAll() {
		$deleteItems = $_POST['ssn-sample-grid_c0'];
		$shouldDelete = array_diff($deleteItems, $this->cannotDelete);

		if (!empty($shouldDelete)) {
			SsnSample::model()->safeDeleteAll('id in (' . implode(',', $shouldDelete) . ')');
			$this->setNotifyMessage(NotificationType::Success, 'Your selected records have been deleted');
		} else
			$this->setNotifyMessage(NotificationType::Error, 'No records was deleted');

		if (!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	public function loadModel($id) {
		//need this define for inherit model case. Form will render parent model name in control if we don't have this line
		$model = SsnSampleSearch::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $model;
	}

}

source/ssn_binh_uat/protected/modules/admin/views/sample/_search.php
<?php $form = $this->beginWidget('CActiveForm', array(
    'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
	'htmlOptions' => array('class' => 'form-horizontal', 'role' => 'form', 'id' => 'search-form'),
)); ?>
<div class="form-group row">
	<div class="col-md-3">
		<?php echo $form->textField($model,'key',array('class'=>'form-control', 'placeHolder' => 'Text to search')); ?>
	</div>
	<div class="col-md-3">
		<?php $this->widget('zii.widgets.jui.CJuiDatePicker',array(
			'model' => $model,
			'attribute' => 'fromDate',
			'options' => array(
				'dateFormat' => 'dd/mm/yy',
			),
			'htmlOptions'=>array(
				'class'=>'form-control fromDate',
				'placeHolder' => 'From'
			),
		)); ?>
	</div>
	<div class="col-md-3">
		<?php $this->widget('zii.widgets.jui.CJuiDatePicker',array(
			'model' => $model,
			'attribute' => 'toDate',
			'options' => array(
				'dateFormat' => 'dd/mm/yy',
			),
			'htmlOptions'=>array(
				'class'=>'form-control toDate',
				'placeHolder' => 'To'
			),
		)); ?>
	</div>
	<div class="col-md-1">
		<button type="submit" class="btn btn-default btn-sm">Search</button>
	</div>
</div>
<?php $this->endWidget(); ?>

source/ssn_binh_uat/protected/modules/admin/views/sample/index.php
<?php
$this->breadcrumbs = array(
    $this->pluralTitle,
);

Yii::app()->clientScript->registerScript('search', "

$( document ).ajaxComplete(function() {


$('#ssn-sample-grid .table tbody tr td').click(function() {
        if ($(this).hasClass('checkbox-column') == false) {
            var row = $(this).parent(0);
            console.log(row);
            id = row.children('.checkbox-column').children('.select-on-check').val();
            location.href ='".$this->createUrl('view')."/id/'+id;
        }
    });

});

$('#ssn-sample-grid .table tbody tr td').click(function() {
        if ($(this).hasClass('checkbox-column') == false) {
            var row = $(this).parent(0);
            console.log(row);
            id = row.children('.checkbox-column').children('.select-on-check').val();
            location.href ='".$this->createUrl('view')."/id/'+id;
        }
    });


$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});

$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('ssn-sample-grid', {
                url : $(this).attr('action'),
		data: $(this).serialize()
	});
	return false;
});

$('#clearsearch').click(function(){
	var id='search-form';
	var inputSelector='#'+id+' input, '+'#'+id+' select';
	$(inputSelector).each( function(i,o) {
		 $(o).val('');
	});
	var data=$.param($(inputSelector));
	$.fn.yiiGridView.update('ssn-sample-grid', {data: data});
	return false;
});

$('.deleteall-button').click(function(){
        var atLeastOneIsChecked = $('input[name=\"ssn-sample-grid_c0[]\"]:checked').length > 0;
        if (!atLeastOneIsChecked)
        {
                alert('Please select at least one record to delete');
        }
        else if (window.confirm('Are you sure you want to delete the selected records?'))
        {
                document.getElementById('ssn-sample-grid-bulk').action='" . Yii::app()->createAbsoluteUrl('admin/' . Yii::app()->controller->id . '/deleteall') . "';
                document.getElementById('ssn-sample-grid-bulk').submit();
        }
});

");

Yii::app()->clientScript->registerScript('ajaxupdate', "
    $('#ssn-sample-grid a.ajaxupdate').on('click', function() {
        $.fn.yiiGridView.update('ssn-sample-grid', {
            type: 'POST',
            url: $(this).attr('href'),
            success: function() {
                $.fn.yiiGridView.update('ssn-sample-grid');
            }
        });
        return false;
    });
");
?>

<script>



</script>
<div class="box">
	<div class="box-body">
		<div class='search-form'>
		<?php $this->renderPartial('_search', array(
			'model' => $model,
		)); ?>
		</div>		
		
		<p>
			<?= CHtml::htmlButton('<span class="glyphicon glyphicon-trash"></span> Bulk Delete', array(
			'class' => 'btn btn-danger deleteall-button', 
			'type' => 'button')); ?>
		</p>
		
		<div class="table-responsive">
        <?php
        $allowAction = in_array("delete", $this->listActionsCanAccess) ? 'CCheckBoxColumn' : '';
        $columnArray = array();
        if (in_array("Delete", $this->listActionsCanAccess)) {
            $columnArray[] = array(
                'value' => '$data->id',
                'class' => "CCheckBoxColumn",
            );
        }
        $columnArray = array_merge($columnArray, array(
            array(
                'header' => 'S/N',
                'type' => 'raw',
                'value' => '$this->grid->dataProvider->pagination->currentPage * $this->grid->dataProvider->pagination->pageSize + ($row+1)',
                'headerHtmlOptions' => array('width' => '30px', 'style' => 'text-align:center;'),
                'htmlOptions' => array('style' => 'text-align:center;')
            ),
            array(
                'header'=>'Send Date',
                'name'=>'send_date',
                'value'=>'date("d/m/Y", strtotime($data->send_date))',
                'htmlOptions' => array('style' => 'text-align:left;')
            ),

            array('header'=>'Sender',
                'name'=>'sender_email',
                'value'=>' $data->sender->company ? $data->sender->company->name:"-"' ,
                'htmlOptions' => array('style' => 'text-align:left;'),
            ),
            array(
                'name' => 'awbn',
                'htmlOptions' => array('style' => 'text-align:left;')
            ),

            array(
                'header'=>'Courier Name',
                'name'=>'search_courier',
                'value'=>'$data->courierName',
                'htmlOptions' => array('style' => 'text-align:left;')
            ),

            /*
            array(
                'header' => 'Actions',
                'class' => 'CButtonColumn',
                'template' => '{view} {delete}',
            ),
            */

        ));
        $form = $this->beginWidget('CActiveForm', array(
            'id' => 'ssn-sample-grid-bulk',
            'enableAjaxValidation' => false,
            'htmlOptions' => array('enctype' => 'multipart/form-data')));

        $this->widget('zii.widgets.grid.CGridView', array(
            'id' => 'ssn-sample-grid',
            'dataProvider' => $model->searchAdmin(),
			'selectableRows' => 2,
            'columns' => $columnArray,
			'cssFile'=>false,
			'itemsCssClass'=>'table table-striped table-bordered',
			'pagerCssClass'=>'pag-container',
			'pager' => array(
				'header'=>'',
				'cssFile' => false,
				'nextPageLabel' => 'Next',
				'prevPageLabel' => 'Previous',
				'firstPageLabel' => 'First',
				'lastPageLabel' => 'Last',
				'selectedPageCssClass'=>'active',
				'maxButtonCount' => 10,
				'htmlOptions'=>array('class' => 'pagination pull-right',)
			),
		));
        $this->endWidget();
        ?>			
		</div>
	</div>
<div>


source/ssn_binh_uat/protected/modules/admin/views/sample/view.php
<?php
$this->breadcrumbs = array(
    'Samples' => array('index'),
    'Sample Detail',
);
?>
<div class="box">
	<div class="box-body">
		<?php $form=$this->beginWidget('CActiveForm', array(
			'id'=>'ssn-sample-form',
			'enableAjaxValidation'=>false,
			'enableClientValidation'=>true,
			'clientOptions'=>array(
				'validateOnSubmit'=>true,
			),
			'htmlOptions' => array(
				'role' => 'form', 
				'enctype' => 'multipart/form-data'
			),
		)); ?>
		<div class="form-group">
            <div class="row">
			 <div class="col-sm-4">
                <?php echo $form->labelEx($model,'dateSentText', array('class'=>'control-label')); ?>
			<p class="form-control-static"><?= $model->dateSentText ?></p>
            </div>
                <div class="col-sm-4">

                    <?php echo $form->labelEx($model,'attention', array('class'=>'control-label')); ?>
                    <p class="form-control-static"><?= $model->attention ?: 'Not set.' ?></p>
                    </div>
            </div>
		</div>

		<!--send from-->

        <div class="form-group">
            <div class="row">

                <div class="col-sm-4">
                    <?php echo $form->labelEx($model,'from_user_id', array('class'=>'control-label')); ?>
                    <p class="form-control-static">
                        <a href="<?= $this->createUrl('company/view', array('id'=> $model->sender->company->id)) ?>"
                           class="notranslate"><?= $model->sender->company->name ?></a>
                    </p>
                </div>
                <div class="col-sm-4">
                    <label for="">Recipient</label>
                    <p class="form-control-static">
                        <?php foreach ($model->receivers as $receiver): ?>
                            <a href="<?= $this->createUrl('company/view', array('id'=> $receiver->company->id)) ?>">
                                <?= $receiver->company->name ?>
                            </a><br/>
                        <?php endforeach ?>
                    </p>
                </div>

            </div>
        </div>



		<div class="form-group">

            <div class="row">
                <div class="col-sm-4">
                    <?php echo $form->labelEx($model,'awbn', array('class'=>'control-label')); ?>
                    <?php if ($model->getTrackingLink()): ?>
                        <p class="form-control-static"><a href="<?= $model->getTrackingLink() ?>" target="_blank"><?= $model->awbn ?></a></p>
                    <?php else: ?>
                        <p class="form-control-static"><?= $model->awbn ?: 'Not set.' ?></p>
                    <?php endif ?>
                </div>
                <div class="col-sm-4">
                    <?php echo $form->labelEx($model,'courier_id', array('class'=>'control-label')); ?>
                    <p class="form-control-static"><?= $model->getCourierName() ?></p>
                </div>
            </div>

		</div>



		<div class="form-group">
            <div class="row-container">
			<label for="" class="control-label">Item</label>
			<div class="table-responsive">
				<table class="item-list table table-bordered table-hover">
					<thead>
						<tr>
							<th>Name</th>
							<th>Color</th>
							<th>Qty</th>
							<th>Unit</th>
							<th>Document</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach($model->items as $index => $item): ?>
						<tr>
							<td class=""><p style="word-break: break-all;"><?= $item->name ?></p></td>
							<td><?= $item->color ?></td>
							<td><?= $item->quantity ?></td>
							<td><?= $item->unit ?></td>
							<td>
								<?php if ($url = $item->getDocumentDownloadUrl()): ?>
								<a href="<?= $url ?>"><?= $item->document ?></a> 
								<?php else: ?>
								No document uploaded.
								<?php endif ?>
							</td>
						</tr>
						<?php endforeach ?>
					</tbody>
				</table>
			</div>
            </div>
		</div>
        <div class="form-group">
            <?php echo $form->labelEx($model,'dateSentText', array('class'=>'control-label')); ?>
            <p class="form-control-static"><?= $model->dateSentText ?></p>

        </div>
		<div class="form-group">
			<?php echo $form->labelEx($model,'document', array('class'=>'control-label')); ?>
			<?php if ($url = $model->getDocumentDownloadUrl()): ?>
			<p><a href="<?= $url ?>" class="notranslate"><?= $model->document ?></a></p>
			<?php else: ?>
			<p class="form-control-static">No document uploaded.</p>
			<?php endif ?>
		</div>	
		<?php $this->endWidget(); ?>
	</div>
</div>